baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "Bimasoft | Aplikasi Ujian Simulasi Mandiri"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Bimasoft | Aplikasi Ujian Simulasi Mandiri"
  author = "Yokowasis"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/egbD0j3"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Product"
    placeholder_about_the_project = "Keperluan"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "Simulasi Mandiri Offline"
      title  = "Aplikasi Simulasi Mandiri Offline"
    [[params.contactForm.projectType]]
      value = "Sistem Manajemen Mandiri Sekolah"
      title  = "Sistem Manajemen Mandiri Sekolah"
    [[params.contactForm.projectType]]
      value = "PPDB"
      title  = "PPDB"
    [[params.contactForm.projectType]]
      value = "Aplikasi Ujian CBT Online"
      title  = "Aplikasi Ujian CBT Online"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/scott-graham-5fNmWej4tAA-unsplash.jpg"
    heading               = "PUSH THE WEB TO THE LIMIT"
    tagline               = "UNTUK MASA DEPAN YANG LEBIH BAIK"
    primary_button        = "SOFTWARE UJIAN"
    primary_button_url    = "portfolio"
    secondary_button      = "MANAJEMEN MANDIRI"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "OUR PROJECTs"
    subtitle  = "Beberapa aplikasi yang bisa dipesan melalui Client Area"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "ORDER NOW"
    primary_button      = "PEMESANAN"
    primary_button_url  = "https://client.bimasoft.web.id/"
    secondary_button    = "CONTACT"
    secondary_button_url = "contact"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Jln. Muhajirin II Kel. Rabangodu Utara Kec. Raba Kota Bima"
      phone   = "+628234-003-9781"
      email   = "info@bimasoft.web.id"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Bimasoft"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Products"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Whatsapp"
          url  = "https://wa.me/6282340039781"
        [[params.footer.social.link]]
          name = "Telegram"
          url  = "https://t.me/6282340039781"
        [[params.footer.social.link]]
          name = "Facebook"
          url  = "https://fb.me/yoko.wasis"
      # Footer Service
      [params.footer.service]
        title       = "About us:"
        description = "Menyediakan aplikasi yang berkaitan dengan dunia pendidikan, mulai dari <span class='text-dark'>ujian</span> sampai <span class='text-dark'>pembayaran spp</span> dan surat menyurat."